services:
  app:
    build: .
    image: nodejs
    ports:
      - "5000:5000"
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./var/www/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
